### ISSUE TITLE
Move deflate crate to image-rs org?

### ISSUE THREAD

**Issue by oyvindln** [image-rs/organization#5]
Would you be interested in/okay with taking ownership of [deflate](https://crates.io/crates/deflate) as well? It's used in png decoding together with the inflate crate that is already under the image org. I dislike being the sole person with commit access to it, and since inflate is already hosted here I think it would make sense to move that one here as well.

**Comment by 197g** [comment]
Sounds possible, definitely interested. Having more dependencies under a single organizational structure does makes sense to me also due to [bus factor](https://en.wikipedia.org/wiki/Bus_factor). The customary configuration would be publish for [the publish team](https://github.com/orgs/image-rs/teams/publish) while keeping your access the same as project lead, and contributor acess to the git repository itself. Does it sound like a favorable way to setup publishing, repo access otherwise we could slightly differ from that?

**Comment by oyvindln** [comment]
That sounds good to me.

**Comment by 197g** [comment]
You could use [this issue from `imageproc`](https://github.com/image-rs/imageproc/issues/318) as a short guide to the transition. One main point is that permissions for a team can only be added by a team member but otherwise it should be straightforward.

**Comment by oyvindln** [comment]
Okay, so I add the image-rs team + you and fintelia as owners of the crate, and transfer the repo to image-rs?

**Comment by 197g** [comment]
That's how I understand the process. [Here is some more information on adding owners](https://doc.rust-lang.org/cargo/reference/publishing.html#managing-a-cratesio-based-crate). As soon as the crate is under the organization the rest of the setup will be done by administrators. I'm not completely sure if you need to be part of the `image-rs` organization to move the repository, you'll get an invite in any case if you want.

**Comment by oyvindln** [comment]
It seems I need to have permission to create repositories under `image-rs`. I presume I would need to be invited to ìmage-rs` and given permission to create a repository. The permission can be remove once the repo is transfered.

**Comment by 197g** [comment]
Right, I forgot. Invite should be sent now, it's not a problem, quite the opposite if you've basically contributed a whole crate to the org :)

**Comment by oyvindln** [comment]
Okay, the repository is transfered. I wasn't sure what to set on the permissions page though, so you may want to change that if needed.

I've also (tried at least) invited image-rs:publish as an owner on crates.io

**Comment by 197g** [comment]
Don't know if that works directly, you need to invite me directly so I can add the team. I think teams can only be added by a member of said team.

**Comment by 197g** [comment]
Before I forget, if you have the time you can also add a project page to [the `image-rs` overview](https://github.com/image-rs/image-rs.github.io). There is no particular guide (yet) but other projects (in the `_projects` and `_summaries` directories) should give a rough overview of the structure and we can sort the rest out in PR/draft comments.

**Comment by birktj** [comment]
Just a small idea here: should we now try to merge the `inflate` and `deflate-rs` crates so that we can have one crate that does both DEFLATE compression and decompression?
