### ISSUE TITLE
Move jpeg-decoder crate to image-rs org?

### ISSUE THREAD

**Issue by kaksmet** [image-rs/organization#9]
I don't have enough time to maintain jpeg-decoder anymore.
Would you be interested in taking ownership of [jpeg-decoder](https://crates.io/crates/jpeg-decoder)?

**Comment by fintelia** [comment]
Yes, we'd be open to taking ownership. jpeg-decoder is currently the last of the Rust image decoding crates that isn't part of the image-rs, so the transfer would also mean that they are all under a single organization

**Comment by kaksmet** [comment]
I've transfered the repository to the image-rs org and invited @fintelia to be an owner of the crate.
I couldn't add image-rs:publish as an owner since I'm not a member of that team, so @fintelia will have to do that.

**Comment by fintelia** [comment]
I accepted the invite and added `github:image-rs:publish`. Thanks!
